/// <!-- Vendor -->
/// <reference path="../../../servicepulse.host/app/js/modules/dist/shell.dist.js" />
/// <reference path="../../../servicepulse.host/app/js/modules/dist/monitoring.dist.js" />
/// <!-- App -->
/// <reference path="../../../servicepulse.host/app/js/app.js" />
/// <reference path="../../../servicepulse.host/app/js/app.constants.js" />
/// <reference path="../../../servicepulse.host/app/js/app.route.js" />
/// <reference path="../../../servicepulse.host/app/js/app.controller.js" />
/// <reference path="../../../servicepulse.host/app/js/app.logging.js" />
/// <reference path="../../../servicepulse.host/app/js/app.http.js" />
/// <!-- Services -->
/// <reference path="../../../servicepulse.host/app/js/services/services.module.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.exception-handler.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.notifications.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.platform-update.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.semver.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.service-control.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.stream.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.uri.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.listener.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.notifier.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.shareddata.js" />
/// <!-- Directives -->
/// <reference path="../../../servicepulse.host/app/js/directives/ngClip.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/moment.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.hud.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.productVersion.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.busy.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.nodata.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.confirmclick.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.tabset.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.tab.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.eatclick.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.failedMessageTabs.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.largenumber.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.multi-checkboxlist.js" />
/// <!-- Mystery -->
/// <reference path="../../../servicepulse.host/app/js/views/event_log_items/eventLogItems.js" />
/// <!-- Archive -->
/// <reference path="../../../servicepulse.host/app/js/views/about/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/about/controller.js" />
/// <!-- Dashboard -->
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.controller.js" />
/// <!-- Failed Groups -->
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/service.js" />
/// <!-- Failed Messages -->
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/service.js" />
/// <!-- Archive -->
/// <reference path="../../../servicepulse.host/app/js/views/archive/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/archive/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/archive/service.js" />
/// <!-- Custom Checks -->
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.controller.js" />
/// <!-- Endpoints -->
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.controller.js" />
/// <!-- Configuration -->
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.service.js" />
/// <!-- Redirects -->
/// <reference path="../../../servicepulse.host/app/js/views/redirect/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/redirect/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/redirect/service.js" />
/// <reference path="../../../servicepulse.host/app/js/views/redirect/edit/controller.js" />
/// <!-- Message -->
/// <reference path="../../../servicepulse.host/app/js/views/message/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/message/route.js" />

/// <reference path="angular-mocks.js" />