/// <!-- Vendor -->
/// <reference path="../../../servicepulse.host/app/lib/jquery/dist/jquery.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/signalr/jquery.signalR.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/angular/angular.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/angular-route/angular-route.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/angular-animate/angular-animate.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/angular-sanitize/angular-sanitize.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/ngStorage/ngStorage.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/ng-page-title/dist/ng-page-title.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/toaster/toaster.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/ng-infinite-scroll/build/ng-infinite-scroll.min.js" />
/// <reference path="../../../servicepulse.host/app/lib/bootstrap/dist/js/bootstrap.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/angular-bootstrap/ui-bootstrap-tpls.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib-manual/page-width-functions.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/zeroclipboard/dist/ZeroClipboard.min.js" /> 
/// <reference path="../../../servicepulse.host/app/lib/momentjs/min/moment.min.js" />
/// <reference path="../../../servicepulse.host/app/lib/angular-momentjs/angular-momentjs.js" />
/// <!-- App -->
/// <reference path="../../../servicepulse.host/app/js/app.js" />
/// <reference path="../../../servicepulse.host/app/js/app.constants.js" />
/// <reference path="../../../servicepulse.host/app/js/app.route.js" />
/// <reference path="../../../servicepulse.host/app/js/app.controller.js" />
/// <reference path="../../../servicepulse.host/app/js/app.logging.js" />
/// <reference path="../../../servicepulse.host/app/js/app.http.js" />
/// <!-- Services -->
/// <reference path="../../../servicepulse.host/app/js/services/services.module.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.exception-handler.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.notifications.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.platform-update.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.semver.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.service-control.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.stream.js" />
/// <reference path="../../../servicepulse.host/app/js/services/services.uri.js" />
/// <reference path="../../../servicepulse.host/app/js/services/service.toast.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.listener.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.notifier.js" />
/// <reference path="../../../servicepulse.host/app/js/services/factory.shareddata.js" />
/// <!-- Directives -->
/// <reference path="../../../servicepulse.host/app/js/directives/ngClip.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/moment.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.hud.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.productVersion.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.busy.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.nodata.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.confirmclick.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.tabset.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.tab.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.eatclick.js" />
/// <reference path="../../../servicepulse.host/app/js/directives/ui.particular.failedMessageTabs.js" />
/// <!-- Mystery -->
/// <reference path="../../../servicepulse.host/app/js/views/event_log_items/eventLogItems.js" />
/// <!-- Archive -->
/// <reference path="../../../servicepulse.host/app/js/views/about/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/about/controller.js" />
/// <!-- Dashboard -->
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/dashboard/dashboard.controller.js" />
/// <!-- Failed Groups -->
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_groups/service.js" />
/// <!-- Failed Messages -->
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/failed_messages/service.js" />
/// <!-- Archive -->
/// <reference path="../../../servicepulse.host/app/js/views/archive/route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/archive/controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/archive/service.js" />
/// <!-- Custom Checks -->
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/custom_checks/customChecks.controller.js" />
/// <!-- Endpoints -->
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/endpoints/endpoints.controller.js" />
/// <!-- Configuration -->
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.module.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.route.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.controller.js" />
/// <reference path="../../../servicepulse.host/app/js/views/configuration/configuration.service.js" />
/// <reference path="angular-mocks.js" />