FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-20191008-windowsservercore-ltsc2019

RUN powershell -NoProfile -Command Add-WindowsFeature web-server, web-webserver
RUN powershell -NoProfile -Command Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe" -OutFile "C:\ServiceMonitor.exe"
RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

WORKDIR /inetpub/wwwroot

EXPOSE 80

ADD ServicePulse.Host/app .

ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
