FROM microsoft/iis

RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

WORKDIR /inetpub/wwwroot

ADD ServicePulse.Host/app .

RUN powershell -NoProfile -Command Remove-Item -Recurse /inetpub/wwwroot/js/config/*